### ISSUE TITLE
KaTeX is very limited

### ISSUE THREAD

**Issue by szhorvat** [abejfehr/markdown-preview-katex#6]
This is just a comment rather than a bug report:

KaTeX is unfortunately extremely limited in what it can render, which makes it rather inconvenient in practice.  markdown-preview-plus did use KaTeX originally, but this made it not very useful for actual mathematical note-taking.  Some details are discussed [here](https://github.com/atom/markdown-preview/issues/116)

**Comment by abejfehr** [comment]
Yup, KaTeX was extremely limited. It's definitely getting much better now though, and I find that it's useful for notes. [This comment](https://github.com/atom/markdown-preview/issues/116#issuecomment-62060938) where you mentioned missing symbols has mostly been addressed by [this release of KaTeX](https://github.com/Khan/KaTeX/releases/tag/v0.2.0).

**Comment by szhorvat** [comment]
Good to know, I should try it again!

**Comment by ghost** [comment]
KaTeX still does not support the dollar sign and euro sign, which I would like to use a lot in my notes..

**Comment by abejfehr** [comment]
The dollar sign should be supported. Try typing the following into their [homepage](http://khan.github.io/KaTeX/):

```
\$4.75 \times 10\%
```

However in this plugin the dollar signs may need to be escaped twice(eg. `\\$`) for the first time in an expression because of the way they're parsed. This is a serious issue and needs to be looked at.

However, you're correct in saying that the Euro symbol is not yet supported. Perhaps you can create an issue on [KaTeX's repository](https://github.com/khan/katex/issues) for that, since I don't see an existing one.

**Comment by ghost** [comment]
Thank you very much! I will create the issue.

**Comment by abejfehr** [comment]
No problem! :)

I actually just read about it and it seems like incorporating the Euro symbol would be [harder than expected](https://en.wikibooks.org/wiki/LaTeX/Special_Characters#Euro_.E2.82.AC_currency_symbol) since it's in another package entirely. I hope they're able to accommodate this request anyway, it would be very useful.

**Comment by ghost** [comment]
if someone could add the eurosign in one of the font files, I can add the eurosign in katex, hopefully according to \eurosym with \euro and \EUR{}
http://www.theiling.de/eurosym.html
